per_page: 8
row: 6
icons_search: search
icons_cached: cached
icons_done: done
icons_https: https
icons_access_time: access_time
show_limit:
  show_10: 10
  show_20: 20
  show_30: 30
  show_50: 50
per_page_50: 50
